language: java
jdk:
- openjdk8
script:
- mvn clean verify -B -f se.bitcraze.crazyflie.lib-target/pom.xml
- ant -f se.bitcraze.crazyflie.lib-target/fixTargetDefinition.xml
- mvn clean verify -B -f se.bitcraze.crazyflie.lib-parent/pom.xml
