# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate target platform P2 repository
      run: mvn -B clean verify -f se.bitcraze.crazyflie.lib-target/pom.xml
    - name: Fix the path to the target platform P2 repository
      run: ant -f se.bitcraze.crazyflie.lib-target/fixTargetDefinition.xml
    - name: Build with Maven
      run: mvn -B clean verify --file se.bitcraze.crazyflie.lib-parent/pom.xml -Dmaven.test.failure.ignore=true
    - name: Publish JUnit results
      uses: ashley-taylor/junit-report-annotations-action@1.3
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: se.bitcraze.crazyflie.lib/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
